name: general_env
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - pip=23.2.*
  - pip:
    - numpy==1.22.*
    - mlflow==2.4.1
    - azureml-mlflow==1.53.0
    - azureml-core==1.53.*
    - azureml-defaults==1.53.*
    - scikit-learn==1.3.*
    - azure-ai-ml==1.9.0
    - requests==2.31.*
    - azure-identity==1.14.0
    - scipy==1.7.1
    - pandas==1.4.4
    - shap==0.42.1
    - joblib==1.3.2
    - seaborn==0.11.2
    - matplotlib==3.4.*
    - shapely==2.0.*
    - scikit-optimize==0.9.*
    - mldesigner==0.1.0b4
